on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          architecture: x64

      - run: flutter build apk --release --split-per-abi

      - run: |
          cd build/app/outputs/apk/release
          mv app-armeabi-v7a-release.apk SysAdmin-development.apk
          mv app-arm64-v8a-release.apk SysAdmin-arm64-development.apk
          mv app-x86_64-release.apk SysAdmin-x86_64-development.apk

      # Step to generate and create the TAG variable
      - name: Generate version tag
        run: |
          TAG=v0.$(printf "%02d" $((GITHUB_RUN_NUMBER)))
          echo "TAG=$TAG" >> $GITHUB_ENV

      # Step to use the TAG variable for release
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*"
          tag: ${{ env.TAG }}  # Using the TAG variable created earlier
          token: ${{ secrets.TOKEN }}
